### ISSUE TITLE
lookup for `.verb.md` in upper directories (same as for verbfile.js)

### ISSUE THREAD

**Issue by tunnckoCore** [verbose/verb-readme-generator#3]
I'm thinking it can be easy and quick addition.

For example

```
/home/charlike/dev
- foo
  - .verb.md
  - bar
    + project
      - index.js
      - LICENSE
      - test.js
    + aaa
    + bbb
  - ccc
- baz
- qux
```

I'm always trying to low the dotfiles and such things and in same time I realize why they are (good and) need - for the contributors. But actually we can agree on that in most cases they don't have job with verb - meaning, only in rare cases they can fix some documentation bug or something.

That's why i'm suggesting to allow verb.md lookup in upper directories. Then we can just have one .verb.md in our home dir.

Buuuut, yea, this may cost time. But in another hand, we can save it globally.

edit: in short: in anyway it's your (owner) job to regenerate the docs and publish a new version.

**Comment by jonschlinkert** [comment]
> Then we can just have one .verb.md in our home dir.

I implemented this, but I fwiw sincerely hope that no one does what you just said. That's a terrible practice. what's the point? you could only use it once and contributors would never be able to update documentation - unless you didn't need or plan to use a template at all. in which case, again, what's the point?

**Comment by tunnckoCore** [comment]
Haha. I don't think it so terrible. And yea, I said it, contributors won't be able to update docs, but there are many libs and projects that just don't need - changing docs may be rare case (even more from user). That's why we use so much automation, there's almost no mistakes. But yea, make sens to have .verb.md in bigger (or hot) libs / projects.

**Comment by jonschlinkert** [comment]
I remember when grunt first came out, this reminds me of how some devs wanted a single, globally installed gruntfile to run all of their linting tasks, because "it's not needed on every project". 

now I know why you have so many issues compared to us lol

**Comment by tunnckoCore** [comment]
> now I know why you have so many issues compared to us lol

Ahahah, why, because I don't know? 

And if i have answer.. it is because you forget too much, jk. :beer: 
The problems wasn't in my side in most cases, srsly. Problems are because you working almost completely locally or when you push it - forgot to publish or have lint errors.
Try `pre-commit`, i tried it and loved it before few weeks - complete awesomeness!

_(i'm not aggressive)_

Cheers,
Charlike!

**Comment by jonschlinkert** [comment]
> (i'm not aggressive)

haha, I know. I was jk
