### ISSUE TITLE
it sets author.username to be organization name

### ISSUE THREAD

**Issue by tunnckoCore** [verbose/verb-readme-generator#4]
I'm not sure how exactly to debug it, but it somewhere in [verb-repo-data#L14-17](https://github.com/verbose/verb-repo-data/blob/master/index.js#L10-L24) or `repo-utils` the `.username()` method, from first glance look.

I've just updated to latest verb#dev and ran `verb` on repo which is from organization, not from my own account.

**Comment by tunnckoCore** [comment]
And that's my package.json start

```js
{
  "name": "limon",
  "version": "0.3.3",
  "description": "The pluggable JavaScript lexer on per character basis.",
  "repository": "limonjs/limon",
  "author": "Charlike Mike Reagent <@tunnckoCore> (http://www.tunnckocore.tk)",
  "precommit.silent": true
}
```

**Comment by tunnckoCore** [comment]
Hm. Maybe it make sense. When I rethink it, it is bit strange how to access my username, haha. Because.. my template build links to services and to my own profile. So in my account repos I just set something like 

```markdown

[npmjs-url]: https://www.npmjs.com/package/{%= name %}
[npmjs-img]: https://img.shields.io/npm/v/{%= name %}.svg?label={%= name %}

[license-url]: https://github.com/{%= repository %}/blob/master/LICENSE
[license-img]: https://img.shields.io/npm/l/{%= name %}.svg

[downloads-url]: https://www.npmjs.com/package/{%= name %}
[downloads-img]: https://img.shields.io/npm/dm/{%= name %}.svg

[author-www-url]: http://www.{%= author.username.toLowerCase() %}.tk
[author-www-img]: https://img.shields.io/badge/www-{%= author.username.toLowerCase() %}.tk-fe7d37.svg

[author-npm-url]: https://www.npmjs.com/~{%= author.username.toLowerCase() %}
[author-npm-img]: https://img.shields.io/badge/npm-~{%= author.username.toLowerCase() %}-cb3837.svg
```

Maybe I should move to author object in package.json to workaround it.

**Comment by tunnckoCore** [comment]
okey, this make sense why changing to author object not worked. There's an issue in repo-utils.username. I'll PR there.

**Comment by jonschlinkert** [comment]
Thanks for debugging and figuring this out!
