### ISSUE TITLE
Some problem with generating TOC

### ISSUE THREAD

**Issue by tunnckoCore** [verbose/verb-readme-generator#6]
I'm experiencing some strange bug with that one. Do you have some ideas?

Im just setting `<!-- toc -->` as needed, run verb, then generated table of contents not includes the headings generated from `apidocs` which actually, is links. I have some heading on same level after the apidocs and it is included.

It's not `markdown-toc` related, i checked.

**Comment by tunnckoCore** [comment]
I'm starting to think that the TOC should be generated on some kind "next tick" after the readme is generated. Because there's one more bug: If you have `# {%= varname %}.foobar` rendered label will be okey, but link to that heading would be wrong.

```md
### `{%= varname %}.Promise`
```

will output `* [`{%= varname %}.Promise`](#-----varname---promise-)` - wrong link to heading

**Comment by jonschlinkert** [comment]
It's not related to async or anything like that. The output is correct since the code comments aren't rendered yet when the toc is generated, so this is really a code comments issue and/or a `helper-apidocs` issue. When I get the new comments stuff pushed up it will resolve this. Give me some time though, I'm doing everything I can to wrap up generate and verb. The comments are the very next thing on the list (you'll like what I'm doing with them :)

**Comment by jonschlinkert** [comment]
closing since this isn't related to verb-readme-generator

**Comment by tunnckoCore** [comment]
> It's not related to async or anything like that.

Yea, maybe. I meant some process ordering with that "next tick".

Okey, we'll wait :)

**Comment by jonschlinkert** [comment]
> some process ordering with that "next tick"

yeah, but I'm saying it's specifically because we render the TOC **before** the actual templates are rendered. One thing we could.... oh nvm I have an idea. brb

**Comment by tunnckoCore** [comment]
> before the actual templates

exactly.

> One thing we could.... oh nvm I have an idea. brb

Cool, if you can get this done easily, haha.

**Comment by jonschlinkert** [comment]
Cool, this works when a heading is a template (but maybe not in code comments yet, I have an idea for that too):

Inside `verb-toc`, I'll add this:

```js
    opts.linkify = function(token, name, slug) {
      if (/^[{<]%?/.test(name)) {
        var view = app.view('temp', {content: name});
        view.compile(opts);
        token.content = view.fn(app.cache.data);
        token.slug = toc.linkify(token.content);
      }
      return token;
    };
```

**Comment by jonschlinkert** [comment]
> But it will error if the context doesn't exist yet... catch 22

I know how to fix that brb

**Comment by jonschlinkert** [comment]
moving this discussion to https://github.com/verbose/verb-toc/issues/2
